####################
# build
####################
FROM node:20.11.0-alpine AS build

ENV NODE_ENV=build

USER node
WORKDIR /home/node

# copy package.json and yarn.lock
COPY --chown=node:node package.json ./
COPY --chown=node:node yarn.lock ./

# Install all dependencies to build
RUN yarn --frozen-lockfile

# Copy source code
COPY --chown=node:node ../../ .

# Generate the production build.
RUN yarn build

# Install only the production dependencies and clean cache to optimize image size.
RUN yarn --frozen-lockfile --production && yarn cache clean

####################
# production 
####################
FROM node:20.11.0-alpine AS prod

# Set to production environment
ENV NODE_ENV=production

USER node
WORKDIR /home/node


# Copy only the necessary files
COPY --chown=node:node --from=build /home/node/dist dist
COPY --chown=node:node --from=build /home/node/node_modules node_modules

# Start the server using the production build
CMD [ "node", "dist/main.js" ]
