services:
  mongo:
    build: ./docker/mongo/
    restart: unless-stopped
    container_name: $MONGODB_CONTAINER_NAME
    ports:
      - $MONGODB_PORT:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - $MONGODB_VOLUME_PATH:/data/db
    networks:
      - y-chat-network
    healthcheck:
      test: /docker-entrypoint-initdb.d/mongo-init.sh
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  y-chat-network:
    driver: bridge
