version: '3.8'

services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    container_name: $MONGODB_CONTAINER_NAME
    ports:
      - $MONGODB_PORT:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DBNAME
    volumes:
      - $MONGODB_VOLUME_PATH:/data/db
    networks:
      - y-chat-network
  app:
    depends_on:
      - mongo
    container_name: y-chat-be
    restart: on-failure:1
    build: .
    ports:
      - $PORT:$PORT
    networks:
      - y-chat-network
    env_file:
      - ./.env
    volumes:
      - ./secure:/app/secure
    stdin_open: true
    tty: true

networks:
  y-chat-network:
    driver: bridge
    