services:
  mongo:
    build: ./docker/mongo/
    restart: unless-stopped
    container_name: $MONGODB_CONTAINER_NAME
    ports:
      - $MONGODB_PORT:27017
    environment:
      - ROOT_USERNAME=$MONGODB_USER
      - ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - $MONGODB_VOLUME_PATH:/data/db
    networks:
      - y-chat-network

networks:
  y-chat-network:
    driver: bridge
    